In [220]:
# Numpy ----- Numeric Python
import numpy as np

In [221]:
# direct array not available in python
import array

In [222]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [223]:
type(np.array([1,2,3,4]))

numpy.ndarray

In [224]:
# typcasting automaticaticaly in numpy array
np.array([1,2,3,4,'shiva','4+8j'])


array(['1', '2', '3', '4', 'shiva', '4+8j'], dtype='<U11')

In [225]:
np.array([[1,3],[3,4]])

array([[1, 3],
       [3, 4]])

In [226]:
np.array([[1,3],[3,4],[6,7,8]])

C:\Users\Shiva Srivastava\AppData\Local\Temp\ipykernel_3544\1655787997.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,3],[3,4],[6,7,8]])


array([list([1, 3]), list([3, 4]), list([6, 7, 8])], dtype=object)

In [227]:
np.array([[[1,3],[3,4]]])

array([[[1, 3],
        [3, 4]]])

In [228]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [229]:
np.array([[1,3],[3,4]],ndmin=3)

array([[[1, 3],
        [3, 4]]])

In [230]:
np.array([[1,3],[3,4]],dtype=complex)

array([[1.+0.j, 3.+0.j],
       [3.+0.j, 4.+0.j]])

In [231]:
arr=np.array([(1,2),(2,4)],dtype=[('a','<i2'),('b','i8')])

In [232]:
arr

array([(1, 2), (2, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [233]:
arr[0][0]

1

In [234]:
type(arr[0][0])

numpy.int16

In [235]:
arr[0][1]

2

In [236]:
type(arr[0][1])

numpy.int64

In [237]:
arr=np.array([[1,3],[3,4]])

In [238]:
type(arr)

numpy.ndarray

In [239]:
type(arr[0][0])

numpy.int32

In [240]:
np.mat(arr)

matrix([[1, 3],
        [3, 4]])

In [241]:

mat=np.matrix(arr)

In [242]:
lst=[3,4,5,6,7]

In [243]:
np.array([3,4,5,6,7])

array([3, 4, 5, 6, 7])

In [244]:
np.asarray(lst)

array([3, 4, 5, 6, 7])

In [245]:
# In case of asanyarray  if data set provide in any type of array then it cannot provide conversion into arrray
np.asanyarray(lst)

array([3, 4, 5, 6, 7])

In [246]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [247]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [248]:
issubclass(np.matrix,np.ndarray)

True

In [249]:
# deep copy and swallow copy
arr

array([[1, 3],
       [3, 4]])

In [250]:
# swallow copy
a=arr

In [251]:
# deep copy
b=np.copy(arr)

In [252]:
arr[0][0]=67

In [253]:
arr

array([[67,  3],
       [ 3,  4]])

In [254]:
a

array([[67,  3],
       [ 3,  4]])

In [255]:
b

array([[1, 3],
       [3, 4]])

In [256]:
# array is mutable


In [257]:
arr[0:]

array([[67,  3],
       [ 3,  4]])

In [258]:
arr[0]

array([67,  3])

In [259]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [260]:
# Numpy is belong to numpy package where list is part of core python

In [261]:
'''
   0  1  2  3  

0  T  F  F  F  

1  F  T  F  F  

2  F  F  T  F  

3  F  F  F  T  

'''
np.fromfunction(lambda i,j :i==j,(4,4))
 

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [262]:
np.fromfunction(lambda i,j :i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [263]:
np.fromfunction(lambda i,j :i/j,(4,4))
# 1/0 --- inf in numpy  
# 0/0 --- nan is not define meaning in numpy

C:\Users\Shiva Srivastava\AppData\Local\Temp\ipykernel_3544\2013101670.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i,j :i/j,(4,4))
C:\Users\Shiva Srivastava\AppData\Local\Temp\ipykernel_3544\2013101670.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i,j :i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [264]:
[i*i for i in range(5)]
    

[0, 1, 4, 9, 16]

In [265]:
gen=(i*i for i in range(5))

In [266]:
def test(x):
    yield x

In [267]:
test(5)

<generator object test at 0x000002987FAAEB20>

In [268]:
# yield is special kind of keyword in python

In [269]:
np.fromiter(gen,dtype=int)

array([ 0,  1,  4,  9, 16])

In [270]:
np.fromiter(range(5),dtype=int)

array([0, 1, 2, 3, 4])

In [271]:
gen=(i*i for i in range(5))
for i in gen:
    print(i)

0
1
4
9
16


In [272]:
np.fromstring('1,2,3,4,5',sep=',',dtype=int)

array([1, 2, 3, 4, 5])

In [273]:
np.fromstring("456 566 456",sep=" ",dtype=int)

array([456, 566, 456])

In [274]:
np.fromstring("456 345 567 889", sep=" ",dtype=int)

array([456, 345, 567, 889])

In [275]:
lst=[3,4,5,6,7,8]

In [276]:
np.array(lst)

array([3, 4, 5, 6, 7, 8])

In [277]:
type(arr)

numpy.ndarray

In [278]:
arr.ndim

2

In [279]:
arr.size

4

In [280]:
arr.shape

(2, 2)

In [281]:
arr.dtype

dtype('int32')

In [282]:
arr

array([[67,  3],
       [ 3,  4]])

In [283]:
arr=np.array([1,2,3,4])

In [284]:
arr.ndim

1

In [285]:
arr.shape

(4,)

In [286]:
arr.size

4

In [287]:
arr2=np.array([[[1,2,3],[3,4,5]]])

In [288]:
arr2.ndim

3

In [289]:
arr2.shape
# (1,2,3) read as 1 number of (2,3)data

(1, 2, 3)

In [290]:
arr2.size

6

In [291]:
arr4=np.array([[[[1,2,3,4],[4,5,6,7]],[[1,2,4,5],[4,5,6,7]]]])

In [292]:
arr4.shape

(1, 2, 2, 4)

In [293]:
arr4.ndim

4

In [294]:
arr4.size

16

In [295]:
arr4

array([[[[1, 2, 3, 4],
         [4, 5, 6, 7]],

        [[1, 2, 4, 5],
         [4, 5, 6, 7]]]])

In [296]:
list(range(6))

[0, 1, 2, 3, 4, 5]

<pre><b>list(range(7.5))</b>

TypeError                                 Traceback (most recent call last)
Input In [80], in <cell line: 1>()
----> 1 list(range(7.5))

TypeError: 'float' object cannot be interpreted as an integer
</pre>

In [297]:
np.arange(5.5,9,0.3)

array([5.5, 5.8, 6.1, 6.4, 6.7, 7. , 7.3, 7.6, 7.9, 8.2, 8.5, 8.8])

In [298]:
np.arange(3.4,9,-0.3)

array([], dtype=float64)

In [299]:
np.arange(9,6.6,-0.3)
# in lemn term we can say fo floatin it take upper bound but in int not
# but it not for float also

array([9. , 8.7, 8.4, 8.1, 7.8, 7.5, 7.2, 6.9, 6.6])

In [300]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [301]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [302]:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [303]:
np.linspace(2,8)
# if you not specify you need it provide 50 data set

array([2.        , 2.12244898, 2.24489796, 2.36734694, 2.48979592,
       2.6122449 , 2.73469388, 2.85714286, 2.97959184, 3.10204082,
       3.2244898 , 3.34693878, 3.46938776, 3.59183673, 3.71428571,
       3.83673469, 3.95918367, 4.08163265, 4.20408163, 4.32653061,
       4.44897959, 4.57142857, 4.69387755, 4.81632653, 4.93877551,
       5.06122449, 5.18367347, 5.30612245, 5.42857143, 5.55102041,
       5.67346939, 5.79591837, 5.91836735, 6.04081633, 6.16326531,
       6.28571429, 6.40816327, 6.53061224, 6.65306122, 6.7755102 ,
       6.89795918, 7.02040816, 7.14285714, 7.26530612, 7.3877551 ,
       7.51020408, 7.63265306, 7.75510204, 7.87755102, 8.        ])

In [304]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [305]:
np.zeros((2,5,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [306]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [307]:
np.empty((34))

array([1.40989877e-311, 1.40985596e-311, 1.40985597e-311, 1.40985597e-311,
       1.40985597e-311, 1.40985595e-311, 1.40985597e-311, 1.40985597e-311,
       1.40985597e-311, 1.40985597e-311, 1.40985597e-311, 1.40985597e-311,
       1.40985597e-311, 1.40985597e-311, 1.40985597e-311, 1.40985597e-311,
       1.40985597e-311, 1.40985595e-311, 1.40985595e-311, 1.40985595e-311,
       1.40985595e-311, 1.40985595e-311, 1.40985595e-311, 1.40985595e-311,
       1.40985595e-311, 1.40985595e-311, 1.40985595e-311, 1.40985596e-311,
       1.40985595e-311, 1.40985597e-311, 1.40985597e-311, 1.40985594e-311,
       1.40985595e-311, 1.40985595e-311])

In [308]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [309]:
np.linspace(2,4,4, endpoint=False,dtype=int)

array([2, 2, 3, 3])

In [310]:
arr1=np.linspace([1,6],4)
arr1

array([[1.        , 6.        ],
       [1.06122449, 5.95918367],
       [1.12244898, 5.91836735],
       [1.18367347, 5.87755102],
       [1.24489796, 5.83673469],
       [1.30612245, 5.79591837],
       [1.36734694, 5.75510204],
       [1.42857143, 5.71428571],
       [1.48979592, 5.67346939],
       [1.55102041, 5.63265306],
       [1.6122449 , 5.59183673],
       [1.67346939, 5.55102041],
       [1.73469388, 5.51020408],
       [1.79591837, 5.46938776],
       [1.85714286, 5.42857143],
       [1.91836735, 5.3877551 ],
       [1.97959184, 5.34693878],
       [2.04081633, 5.30612245],
       [2.10204082, 5.26530612],
       [2.16326531, 5.2244898 ],
       [2.2244898 , 5.18367347],
       [2.28571429, 5.14285714],
       [2.34693878, 5.10204082],
       [2.40816327, 5.06122449],
       [2.46938776, 5.02040816],
       [2.53061224, 4.97959184],
       [2.59183673, 4.93877551],
       [2.65306122, 4.89795918],
       [2.71428571, 4.85714286],
       [2.7755102 , 4.81632653],
       [2.

In [311]:
arr1.shape

(50, 2)

In [312]:
arr2=np.linspace([1,6],4,endpoint=True,axis=1)
arr2

array([[1.        , 1.06122449, 1.12244898, 1.18367347, 1.24489796,
        1.30612245, 1.36734694, 1.42857143, 1.48979592, 1.55102041,
        1.6122449 , 1.67346939, 1.73469388, 1.79591837, 1.85714286,
        1.91836735, 1.97959184, 2.04081633, 2.10204082, 2.16326531,
        2.2244898 , 2.28571429, 2.34693878, 2.40816327, 2.46938776,
        2.53061224, 2.59183673, 2.65306122, 2.71428571, 2.7755102 ,
        2.83673469, 2.89795918, 2.95918367, 3.02040816, 3.08163265,
        3.14285714, 3.20408163, 3.26530612, 3.32653061, 3.3877551 ,
        3.44897959, 3.51020408, 3.57142857, 3.63265306, 3.69387755,
        3.75510204, 3.81632653, 3.87755102, 3.93877551, 4.        ],
       [6.        , 5.95918367, 5.91836735, 5.87755102, 5.83673469,
        5.79591837, 5.75510204, 5.71428571, 5.67346939, 5.63265306,
        5.59183673, 5.55102041, 5.51020408, 5.46938776, 5.42857143,
        5.3877551 , 5.34693878, 5.30612245, 5.26530612, 5.2244898 ,
        5.18367347, 5.14285714, 5.10204082, 5.0

In [313]:
arr2.shape

(2, 50)

In [314]:
np.logspace(2,3,5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [315]:
np.logspace([2,3],4)

array([[  100.        ,  1000.        ],
       [  109.8541142 ,  1048.11313415],
       [  120.67926406,  1098.54114199],
       [  132.57113656,  1151.39539933],
       [  145.63484775,  1206.79264064],
       [  159.98587196,  1264.85521686],
       [  175.75106249,  1325.71136559],
       [  193.06977289,  1389.49549437],
       [  212.09508879,  1456.3484775 ],
       [  232.99518105,  1526.41796718],
       [  255.95479227,  1599.85871961],
       [  281.1768698 ,  1676.83293681],
       [  308.88435965,  1757.51062485],
       [  339.32217719,  1842.06996933],
       [  372.75937203,  1930.69772888],
       [  409.49150624,  2023.58964773],
       [  449.8432669 ,  2120.95088792],
       [  494.17133613,  2222.99648253],
       [  542.86754393,  2329.95181052],
       [  596.36233166,  2442.05309455],
       [  655.12855686,  2559.5479227 ],
       [  719.685673  ,  2682.69579528],
       [  790.60432109,  2811.76869797],
       [  868.51137375,  2947.05170255],
       [  954.09

In [316]:
np.logspace([2][3].4)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (2391631441.py, line 1)

In [319]:
d=np.linspace(4,7,40)

In [320]:
d

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [321]:
d.shape

(40,)

In [322]:
d.ndim

1

In [323]:
d.T

array([4.        , 4.07692308, 4.15384615, 4.23076923, 4.30769231,
       4.38461538, 4.46153846, 4.53846154, 4.61538462, 4.69230769,
       4.76923077, 4.84615385, 4.92307692, 5.        , 5.07692308,
       5.15384615, 5.23076923, 5.30769231, 5.38461538, 5.46153846,
       5.53846154, 5.61538462, 5.69230769, 5.76923077, 5.84615385,
       5.92307692, 6.        , 6.07692308, 6.15384615, 6.23076923,
       6.30769231, 6.38461538, 6.46153846, 6.53846154, 6.61538462,
       6.69230769, 6.76923077, 6.84615385, 6.92307692, 7.        ])

In [324]:
d.ndim

1

In [325]:
d.shape

(40,)

In [326]:
d.reshape(40,1)

array([[4.        ],
       [4.07692308],
       [4.15384615],
       [4.23076923],
       [4.30769231],
       [4.38461538],
       [4.46153846],
       [4.53846154],
       [4.61538462],
       [4.69230769],
       [4.76923077],
       [4.84615385],
       [4.92307692],
       [5.        ],
       [5.07692308],
       [5.15384615],
       [5.23076923],
       [5.30769231],
       [5.38461538],
       [5.46153846],
       [5.53846154],
       [5.61538462],
       [5.69230769],
       [5.76923077],
       [5.84615385],
       [5.92307692],
       [6.        ],
       [6.07692308],
       [6.15384615],
       [6.23076923],
       [6.30769231],
       [6.38461538],
       [6.46153846],
       [6.53846154],
       [6.61538462],
       [6.69230769],
       [6.76923077],
       [6.84615385],
       [6.92307692],
       [7.        ]])

In [327]:
d.reshape(2,5,4)

array([[[4.        , 4.07692308, 4.15384615, 4.23076923],
        [4.30769231, 4.38461538, 4.46153846, 4.53846154],
        [4.61538462, 4.69230769, 4.76923077, 4.84615385],
        [4.92307692, 5.        , 5.07692308, 5.15384615],
        [5.23076923, 5.30769231, 5.38461538, 5.46153846]],

       [[5.53846154, 5.61538462, 5.69230769, 5.76923077],
        [5.84615385, 5.92307692, 6.        , 6.07692308],
        [6.15384615, 6.23076923, 6.30769231, 6.38461538],
        [6.46153846, 6.53846154, 6.61538462, 6.69230769],
        [6.76923077, 6.84615385, 6.92307692, 7.        ]]])

In [328]:
np.linspace([2,5],4)

array([[2.        , 5.        ],
       [2.04081633, 4.97959184],
       [2.08163265, 4.95918367],
       [2.12244898, 4.93877551],
       [2.16326531, 4.91836735],
       [2.20408163, 4.89795918],
       [2.24489796, 4.87755102],
       [2.28571429, 4.85714286],
       [2.32653061, 4.83673469],
       [2.36734694, 4.81632653],
       [2.40816327, 4.79591837],
       [2.44897959, 4.7755102 ],
       [2.48979592, 4.75510204],
       [2.53061224, 4.73469388],
       [2.57142857, 4.71428571],
       [2.6122449 , 4.69387755],
       [2.65306122, 4.67346939],
       [2.69387755, 4.65306122],
       [2.73469388, 4.63265306],
       [2.7755102 , 4.6122449 ],
       [2.81632653, 4.59183673],
       [2.85714286, 4.57142857],
       [2.89795918, 4.55102041],
       [2.93877551, 4.53061224],
       [2.97959184, 4.51020408],
       [3.02040816, 4.48979592],
       [3.06122449, 4.46938776],
       [3.10204082, 4.44897959],
       [3.14285714, 4.42857143],
       [3.18367347, 4.40816327],
       [3.

In [329]:
np.linspace(2,3)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [330]:
np.logspace(2,5,10) 
# log(x)=2
# x=100
# log(x)=5
# x=100000

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [331]:
np.random.rand(3)

array([0.99875087, 0.77092357, 0.73010996])

In [332]:
np.random.randn(5)

array([ 0.09730317, -0.61277908, -1.14231666, -0.6499891 ,  0.37992634])

In [333]:
np.random.randn(2,2,3)

array([[[ 0.181407  ,  2.02810926, -0.97668799],
        [-0.58051545,  0.23037113, -0.02901317]],

       [[-0.75621614,  0.18364319,  0.23491611],
        [-0.85134033,  0.76752353,  1.25005775]]])

In [334]:
np.random.randint(5)

0

In [335]:
np.random.randint(5,34)

20

In [336]:
np.random.randint(5,60,(4,4))

array([[26,  6, 52,  5],
       [29, 56, 19, 53],
       [20, 34, 25, 55],
       [13, 17, 46, 22]])

In [337]:
arr=np.random.randint(3,9,(3,3))

In [338]:
arr

array([[7, 8, 8],
       [8, 8, 6],
       [6, 4, 4]])

In [339]:
arr.reshape(1,9)

array([[7, 8, 8, 8, 8, 6, 6, 4, 4]])

In [340]:
arr.reshape(3,-1)
# automatically understand what is reamining dimension if you put negative number

array([[7, 8, 8],
       [8, 8, 6],
       [6, 4, 4]])

In [341]:
arr.max()

8

In [342]:
arr.min()

4

In [343]:
# indexing and slicing 
arr=np.random.randint(4,10,(5,5))

In [344]:
arr

array([[6, 9, 9, 5, 6],
       [6, 6, 5, 8, 4],
       [8, 8, 4, 9, 7],
       [4, 8, 4, 6, 5],
       [5, 4, 5, 5, 8]])

In [345]:
arr[3:5,3:5]
# array slicing

array([[6, 5],
       [5, 8]])

In [346]:
arr[:,[1,3]]

array([[9, 5],
       [6, 8],
       [8, 9],
       [8, 6],
       [4, 5]])

In [347]:
arr>5

array([[ True,  True,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True, False],
       [False, False, False, False,  True]])

In [348]:
arr[arr>5]

array([6, 9, 9, 6, 6, 6, 8, 8, 8, 9, 7, 8, 6, 8])

In [349]:
# operation in array


In [350]:
arr*arr

array([[36, 81, 81, 25, 36],
       [36, 36, 25, 64, 16],
       [64, 64, 16, 81, 49],
       [16, 64, 16, 36, 25],
       [25, 16, 25, 25, 64]])

In [351]:
arr1=np.random.randint(3,4,(3,3))
arr1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [352]:
arr2=np.random.randint(3,5,(3,3))
arr2

array([[4, 3, 4],
       [4, 4, 3],
       [4, 3, 3]])

In [353]:
# Multiplication in array
arr1*arr2
# remember shape of arr1 and arr2 must be same

array([[12,  9, 12],
       [12, 12,  9],
       [12,  9,  9]])

In [354]:
# Matrix multiplication
arr1@arr2

array([[36, 30, 30],
       [36, 30, 30],
       [36, 30, 30]])

In [355]:
arr/0

C:\Users\Shiva Srivastava\AppData\Local\Temp\ipykernel_3544\4291252909.py:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [356]:
arr**2

array([[36, 81, 81, 25, 36],
       [36, 36, 25, 64, 16],
       [64, 64, 16, 81, 49],
       [16, 64, 16, 36, 25],
       [25, 16, 25, 25, 64]])

In [357]:
# broadcasting
arr=np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [358]:
a=np.array([1,2,3,4])

In [359]:
a

array([1, 2, 3, 4])

In [360]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [361]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [362]:
b=np.linspace(2,10,12)
b=b.reshape(3,4)

In [363]:
arr+b

array([[ 2.        ,  2.72727273,  3.45454545,  4.18181818],
       [ 4.90909091,  5.63636364,  6.36363636,  7.09090909],
       [ 7.81818182,  8.54545455,  9.27272727, 10.        ]])

In [364]:
# columnwise brodcasting
c=np.array([5,6,7])

In [365]:
d=c.T

In [366]:
c=c.reshape(3,1)

In [367]:
arr+c

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [368]:
d

array([5, 6, 7])

In [369]:
d.shape

(3,)

In [370]:
d.T

array([5, 6, 7])

In [371]:
np.sqrt(arr+9)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [372]:
np.log10(arr+100)

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [373]:
arr1=np.random.randint(2,5,(5,5))

In [374]:
arr1

array([[2, 2, 3, 4, 4],
       [2, 2, 3, 2, 4],
       [4, 2, 4, 2, 2],
       [2, 2, 4, 3, 4],
       [3, 3, 4, 4, 2]])

In [375]:
np.log10(arr1)

array([[0.30103   , 0.30103   , 0.47712125, 0.60205999, 0.60205999],
       [0.30103   , 0.30103   , 0.47712125, 0.30103   , 0.60205999],
       [0.60205999, 0.30103   , 0.60205999, 0.30103   , 0.30103   ],
       [0.30103   , 0.30103   , 0.60205999, 0.47712125, 0.60205999],
       [0.47712125, 0.47712125, 0.60205999, 0.60205999, 0.30103   ]])

In [376]:
np.log2(arr1)

array([[1.       , 1.       , 1.5849625, 2.       , 2.       ],
       [1.       , 1.       , 1.5849625, 1.       , 2.       ],
       [2.       , 1.       , 2.       , 1.       , 1.       ],
       [1.       , 1.       , 2.       , 1.5849625, 2.       ],
       [1.5849625, 1.5849625, 2.       , 2.       , 1.       ]])

In [377]:
np.random.seed(13)

In [378]:
# if you want random data not change use seed
np.random.seed(130)
np.random.rand(2,4)

array([[0.14163027, 0.31154436, 0.55479229, 0.12581142],
       [0.49388258, 0.92112784, 0.37984503, 0.12644965]])